import pandas as pd
import matplotlib.pyplot as plt

# Read the CSV file generated by your C++ program
df = pd.read_csv("timing_comparison.csv")

# Plot execution time versus number of f points within g
plt.figure(figsize=(10, 6))
plt.plot(df["nodes_in_g"], df["time_map_us"], marker='o', label="map_version ")
plt.plot(df["nodes_in_g"], df["time_list_us"], marker='s', label="list_version ")

plt.xlabel("Number of f points within g")
plt.ylabel("Execution time (milliseconds)")
plt.title("Execution Time Comparison: map_version vs list_version")
plt.grid(True)
plt.legend()
plt.tight_layout()
plt.show()

